DROP TABLE book;
DROP TABLE issue;
DROP TABLE reader;
DROP TABLE person;




CREATE TABLE IF NOT EXISTS book
(
    id    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(256) NOT NULL
);

INSERT INTO book (title)
VALUES ('Обломов'),
       ('Братья Карамазовы'),
       ('Мастер и Маргарита'),
       ('Финансист'),
       ('Шинель');


CREATE TABLE IF NOT EXISTS reader
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(256),
    last_name  VARCHAR(256)
);

INSERT INTO reader (first_name, last_name)
VALUES ('Виктор', 'Сергеев'),
       ('Иван', 'Иванов'),
       ('Сергей', 'Серов'),
       ('Станислав', 'Антипов'),
       ('Виталий', 'Антонов');

CREATE TABLE IF NOT EXISTS issue
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    book_id     BIGINT NOT NULL,
    reader_id   BIGINT NOT NULL,
    issued_at   DATE,
    returned_at DATE
);

CREATE TABLE IF NOT EXISTS person
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    login VARCHAR(256),
    password  VARCHAR(256),
    role  VARCHAR(256)
    );

INSERT INTO person (login, password, role)
VALUES ('victor', '123', 'admin'),
       ('ivan', '222', 'user'),
       ('sergey', '444', 'user');