spring:
  application:
    name: HW7

    issue:
      max_allowed_books:
        3
  datasource:
    url: jdbc:postgresql://localhost:5430/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
